- hosts: all
  become: true
  roles:
    - update-cache
    - update-packages
    - install-configure-avahi
    - install-basic-agent-software
- hosts: all
  become: false
  roles:
    - azure-devops-agent